---
title: WizeDom Wisdom.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
Name: WizeDomWisom
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
